# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Antony Polukhin 2014-2016.

#
# See https://svn.boost.org/trac/boost/wiki/TravisCoverals for description of this file
# and how it can be used with Boost libraries.
#
# File revision #6 modified

env:
    matrix:
        - CXX_STANDARD=c++14 TOOLSET=g++-5
        - CXX_STANDARD=c++1z TOOLSET=g++-5
        #- CXX_STANDARD=c++14 TOOLSET=clang++-3.7


###############################################################################################################
# From this point and below code is same for all the Boost libs
###############################################################################################################
sudo: false
language: cpp
compiler:
    - gcc

os:
    - linux

# Installing additional tools
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.7
    packages:
    - valgrind
    - gcc-5
    - g++-5
    #- clang-3.7

script:
    - git clone https://github.com/boostorg/core.git ../boost_core
    - git clone https://github.com/boostorg/assert.git ../boost_assert
    # `--coverage` flags required to generate coverage info for Coveralls
    - for f in test/*.cpp; do $TOOLSET -std=$CXX_STANDARD --coverage -I../boost_core/include/ -I../boost_assert/include/ -I./include/ $f && valgrind ./a.out && rm ./a.out; done
